apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: tankes-story
  name: tankes-exporter-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tankes-exporter-leader-election-role
subjects:
- kind: ServiceAccount
  name: tankes-exporter