apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: {{ .Release.Name }}
    app: tankes-story
  name: tankes-exporter-metrics-monitor
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app.service: tankes-exporter