apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: tankes-exporter
    app: tankes-story
  name: tankes-exporter-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.service: tankes-exporter