apiVersion: v1
kind: Service
metadata:
  labels:
    app: tankes-story
  annotations:
  {{- if and .Values.server.expose.enabled .Values.server.expose.aws.enabled }}
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: {{ .Values.server.expose.aws.elasticAllocationId }}
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  {{- end }}
  name: server
spec:
  selector:
    app: tankes-story-server
  ports:
  - name: login
    port: 8484
    protocol: TCP
    targetPort: 8484
  - name: my-2
    port: 7575
    protocol: TCP
    targetPort: 7575
  - name: my-3
    port: 7576
    protocol: TCP
    targetPort: 7576
  - name: my-5
    port: 7577
    protocol: TCP
    targetPort: 7577
  {{- if .Values.server.expose.enabled }}
  type: LoadBalancer
  {{- end }}